### ISSUE TITLE
Implement Functionality in a User's Join/Leave Button

### ISSUE THREAD

**Issue by sanehirakenji** [ConnectUni/connectuni#104]
Do work for this in issue-104

Currently the Join/Leave button showing up on the list of groups in the "Current User Profile" and "Other User Profile" shows specifically "Join" or "leave". 

Based on the currently logged in user, change this value to be dependent on if a user is in the group or not and update accordingly.

**Comment by michho8** [comment]
In the current user profile, plan to display a modal notifying them that they left the group. Don't need to change the button that says, "Leave." 

In another user's profile, all the buttons say, "Join," even when it's a shared group with the current user. Change the button to be dependent on whether the user is in the group too.

**Comment by michho8** [comment]
On pause because we need to use Firebase to initialize data first - app crashes often
