### ISSUE TITLE
Group Chat Page Breaks if a User Leaves

### ISSUE THREAD

**Issue by sanehirakenji** [ConnectUni/connectuni#105]
Do work for this in issue-105.

Currently, if the currently logged in user leaves a group, the associated group chat page will break. We need to find a way to fix this as otherwise if the user follows the following instructions, the application will provide a red error screen:

My Groups Page >> Clicks on Group >> Group Chat page >> Clicks on Group Info >> Clicks on Leave Group >> Clicks back arrow >> broken app.

**Comment by michho8** [comment]
Plan to just return the user to their Group home page instead of leaving them in the group chat. Want to also implement a modal to indicate they have left the respective group.
