### ISSUE TITLE
Update and implement the UserDB database

### ISSUE THREAD

**Issue by sanehirakenji** [ConnectUni/connectuni#37]
Do work for this in issue-037.

Update and implement the user database we discussed in class on Thursday. It should contain realistic database items as well as getter/setter methods as needed.

**Comment by michho8** [comment]
Bug in this line of code: `return allUsers.firstWhere((user) => user.name == name);` 
This is in the getUserByName function in user.dart. Will not throw error if `user.name` changed to `user.uid`.
We're trying to search the user by their name, not by uid.

Related: ```...usersDB
                .getUsers()
                .map((uName) => UserCardSearch(name: uName.uid)),``` in friendslist and search_people_screen
