### ISSUE TITLE
Standardize the databases formatting. (2 File Divide)

### ISSUE THREAD

**Issue by sanehirakenji** [ConnectUni/connectuni#62]
Do work for this in issue-062.

On Tuesday 10/10, Michelle proposed we divide each database into three different files rather than just one. Once all databases are created, divide them into the two files as listed below:

- [ ] Database Object (Ex. user.dart)
- [ ] List of Database Objects (Ex. usersList.dart)
- [ ] Mockup Database of Objects (EX: put at the end of usersList.dart with a comment to delete later)

**Comment by michho8** [comment]
Refer to [issue-37](https://github.com/ConnectUni/connectuni/issues/37) for the User class example. There are two files: user.dart and userList.dart (includes the mock DB of a UserList).
